### PR TITLE
Review answers

### LINKED ISSUE #54: Create reviwe answers component.
When user click on review answers button, the user will be redirected to the review answers component, which will show questions and the selected answers.

answers can be highlighted for the correct answers with green colour, if wrong it will be highlight red colour.

### PR DESCRIPTION
**Pull request by A-Meri**

### CODE REVIEW

**Review by bonboh — CHANGES_REQUESTED** [review]
Good job getting this working! Got a few suggestions:

- Having an outer card is not so common—let's remove it
- Let's remove `Review answers` and change the `Quiz.js` `CYF quiz` heading to `HTML quiz`. This way we can just have one heading since a heading directly under another heading doesn't look so great. We probably don't need to show the user that they're reviewing answers since we're showing their score so they know they're reviewing answers
- The score could be `Your score: x out of y`, and can be below the heading
- `ol` should only have `li` as children. `ol` on line 23 does not have `li` as children so that means `ol` is wrong here and can be removed since it does not fit here
- Let's put the question text in a `Card.Title`
- The `li` classname has a nested ternary which is not so readable. Let's extract that logic into a function
- There are some redundant margins—let's remove them
- We can remove the `return` keywords since we're returning a single expression
- The `Try again` button looks better as a `primary` variant—let's change it to this

**Review by bonboh — CHANGES_REQUESTED** [review]
Good work on the changes! Got the following comments and suggestions:

- URL paths generally only consist of lowercase letters and hyphens, so we should not be using `/HTML` etc. Let's revert those changes
- For displaying `HTML quiz`, you could create something like the following
  ```javascript
  const quizDisplayText = {
    html: 'HTML',
    css: 'CSS',
    js: 'JavaScript',
  };
  ```
  And use it like `<h1>{quizDisplayText[quizName]} quiz</h1>`
- I can't see the score. Let's put `Your score: x out of y` back in at the top of the `ReviewAnswers` component
- In https://react-bootstrap.github.io/components/cards/, the structure is:
  ```js
  <Card.Body>
    <Card.Title>Card Title</Card.Title>
    <Card.Text>
  ...
  ```
  The `Title` is a sibling of `Text`, not a child of it, so let's change the code to reflect this. I think the title looks better without a background colour so let's remove the `Title` styling
- There are still some redundant margins—let's remove them
- We can remove the `return` keywords inside `questions.map` and `question.answers.map` since they are returning a single expression
- Variable names in JavaScript should always start with a small letter, so let's fix this. The only exceptions are when the variables are classes or are React components
- The `CheckAnswersClass` name is saying "this function will check the answer's class" but that's not true. What the function does is it "gets the answer's class" so it would be more appropriately named something like `getAnswerClass`

**Comment by A-Meri** [comment]
Thank you very much for the feedback, mind me asking :-

There are still some redundant margins—let's remove them, which ones are you referring to!
Thank you :)

**Comment by bonboh** [comment]
> There are still some redundant margins—let's remove them, which ones are you referring to!

There's a couple of `mr` classes in `ReviewAnswers` that are unnecessary because there's no element to the right to create a gap for.

File: src/components/ReviewAnswers.js [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+const ReviewAnswers = ({
+  score,
+  questions,
+  quizName,
+  userAnswers,
+  numOfQuestions,
+}) => {
+  return (
+    <div>
+      <div>
```
Comment (bonboh) [inline src/components/ReviewAnswers.js]: This `div` is not doing anything so it should be removed

File: src/components/ReviewAnswers.js [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+        <h3>
```
Comment (bonboh) [inline src/components/ReviewAnswers.js]: `Your score is....` reads more like a sentence than a heading, so it should probably be in a `p` instead of a `h3`

File: src/components/ReviewAnswers.js [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+          Your score is : {score} / {numOfQuestions}
```
Comment (bonboh) [inline src/components/ReviewAnswers.js]:
```suggestion
          Your score is: {score} / {numOfQuestions}
```
`:`s do not have spaces before them

File: src/components/ReviewAnswers.js [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+        </h3>
+      </div>
+      {questions.map(question => (
+        <Card>
+          <Card.Body>
+            <Card.Title>{question.text}</Card.Title>
+            <Card.Text>
+              <ul>
```
Comment (bonboh) [inline src/components/ReviewAnswers.js]: The `ul` element by default has some margin at the bottom which is adding a bit more space to the bottom of the card. Let's add `mb-0` to remove this extra space

File: src/components/ReviewAnswers.js [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+                  >
+                    {answer.text}
+                  </li>
+                ))}
+              </ul>
+            </Card.Text>
+          </Card.Body>
+        </Card>
+      ))}
+      <Button className="my-2" variant="primary" href={quizName}>
```
Comment (bonboh) [inline src/components/ReviewAnswers.js]: To make the spacing consistent with the `Card`s, we can change this class to `mb-4`

File: src/components/ReviewAnswers.js [hunk 6]
```diff
@@ -0,0 +1,53 @@
...
+}) => {
+  return (
+    <div>
+      <div>
+        <h3>
+          Your score is : {score} / {numOfQuestions}
+        </h3>
+      </div>
+      {questions.map(question => (
+        <Card>
```
Comment (bonboh) [inline src/components/ReviewAnswers.js]: The cards look better with a bit of space between them. We could use `mb-4` here

**Review by bonboh — CHANGES_REQUESTED** [review]
Good job slimming down the code! We're almost ready to merge—just a few more things

File: src/components/ReviewAnswers.js (hunk 5 above)
Comment (AightA) [reply src/components/ReviewAnswers.js:46]: the Try again button will be very close to the card.

File: src/components/ReviewAnswers.js (hunk 6 above)
Comment (A-Meri) [reply src/components/ReviewAnswers.js]: I see now, awesome. done and done :)

**Review by bonboh — APPROVED** [review]
Great job!
